### ISSUE TITLE
Step Functions lab - issue with template

### ISSUE THREAD

**Issue by kgpax** [linuxacademy/aws-cda-2018#1]
When doing the "Creating Your Own Serverless Reminder Service on AWS with Step Functions, API Gateway, Lambda and S3" lab in the AWS CDA 2018 course, the `practice-time-labs/reminder-service-step-functions-api-gateway/step-function-template.json` file contains placeholder values for the task resource ARN, for example:

```
"TextReminder": {
  "Type" : "Task",
  "Resource": "TEXT_REMINDER_ARN",
  "Next": "NextState"
},
```

Perhaps its a new thing in the step functions editor in AWS, but this is not allowed to be saved as it expects this `Resource` value to be a valid lambda or step function ARN format. I got around this by creating a new empty lambda function and using its ARN as a placeholder instead.

**Comment by fernando-mc** [comment]
Hello @kgpax, thanks for the heads up! Looks like AWS recently changed it so that you can't have placeholders when creating state machines that use an ARN.

I went ahead and fixed the lab - basically by having folks wait until the Lambda functions were created to create the state machine. Always appreciate you pointing stuff like this out since I can't always go back and catch these things without folks like you letting me know!
